library(dplyr)
library(tidyverse)
library(xml2)
library(httr)
library(rjson)
library(jsonlite)
library(lubridate)
library(openxlsx)
library(googleAnalyticsR)
library(salesforcer)
library(rvest)
library(conflicted)
library(stringr)
library(dotenv)
library(writexl)
library(jsonlite)
install.packages("remotes")
remotes::install_github("stenevang/sftp", auth_token = NULL)
library(sftp)
install.packages("DBI")
install.packages("RMariaDB")
library(DBI)
library(RMariaDB)



#library(RMySQL)

conflicts_prefer(jsonlite::toJSON)
conflicts_prefer(jsonlite::fromJSON)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::mutate)
conflicts_prefer(dplyr::group_by)
conflicts_prefer(dplyr::summarize)
conflicts_prefer(dplyr::rename)

